services:
  postgres:
    image: postgres:16-alpine
    container_name: demo-facturator-postgres
    environment:
      POSTGRES_DB: demo_facturator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
